# Generated by Django 3.2.8 on 2022-03-22 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("notes", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="projects", name="users"),
        migrations.AddField(
            model_name="projects", name="users", field=models.ManyToManyField(to=settings.AUTH_USER_MODEL)
        ),
    ]
