# Generated by Django 3.2.8 on 2022-03-22 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("notes", "0002_auto_20220322_1830")]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="usertodoapp.customuser"
            ),
            preserve_default=False,
        )
    ]
