# Generated by Django 3.2.8 on 2022-03-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notes", "0003_todo_user")]

    operations = [
        migrations.AddField(
            model_name="projects", name="tryperer", field=models.IntegerField(default=1), preserve_default=False
        )
    ]
