# Generated by Django 3.2.8 on 2022-03-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notes", "0004_projects_tryperer")]

    operations = [migrations.RemoveField(model_name="projects", name="tryperer")]
