# Generated by Django 3.2.8 on 2022-03-26 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0005_remove_projects_tryperer"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="user"),
        migrations.AddField(
            model_name="todo",
            name="creator",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="usertodoapp.customuser"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(model_name="projects", name="link", field=models.URLField(blank=True)),
        migrations.AlterField(model_name="projects", name="title", field=models.CharField(max_length=150, unique=True)),
        migrations.AlterField(
            model_name="todo",
            name="project",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="notes.projects"),
        ),
    ]
