# Generated by Django 3.2.8 on 2022-03-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notes", "0006_auto_20220326_0706")]

    operations = [migrations.RenameField(model_name="todo", old_name="creator", new_name="user")]
