# Generated by Django 3.2.8 on 2022-03-22 20:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("usertodoapp", "0001_initial")]

    operations = [
        migrations.AlterModelManagers(
            name="customuser", managers=[("objects", django.contrib.auth.models.UserManager())]
        )
    ]
